name: ecologist_app
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.4.3
  provider: ^6.0.3
  http: ^0.13.5
  geolocator: ^9.0.1
  flutter_spinkit: ^5.1.0
  rflutter_alert: ^2.0.4
  geocoding: ^2.0.4
  google_maps_flutter: ^2.2.0
  dio: ^4.0.6
  flutter_polyline_points: ^1.0.0
  qr_flutter: ^4.0.0
  json_annotation: ^4.6.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
