// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvTrJkvVCCaLsvXPREFyakiozn0CPplDg',
    appId: '1:580433160519:web:6adf50d4fa13efcd6a0462',
    messagingSenderId: '580433160519',
    projectId: 'ecologistapp-37663',
    authDomain: 'ecologistapp-37663.firebaseapp.com',
    databaseURL: 'https://ecologistapp-37663-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecologistapp-37663.appspot.com',
    measurementId: 'G-JGVZC4SP0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE5JfCzIG62ToDwLsVeIiHykrUrlWwExU',
    appId: '1:580433160519:android:a43dffe9c200088b6a0462',
    messagingSenderId: '580433160519',
    projectId: 'ecologistapp-37663',
    databaseURL: 'https://ecologistapp-37663-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecologistapp-37663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqO4rL2ZlVUzUwRzk3n0kZZVRJTqMqF_Q',
    appId: '1:580433160519:ios:0eaba2c0d73a1c686a0462',
    messagingSenderId: '580433160519',
    projectId: 'ecologistapp-37663',
    databaseURL: 'https://ecologistapp-37663-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecologistapp-37663.appspot.com',
    iosClientId: '580433160519-m1e27jtvng9rgrib8plco2d5tj9nd0j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecologistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqO4rL2ZlVUzUwRzk3n0kZZVRJTqMqF_Q',
    appId: '1:580433160519:ios:0eaba2c0d73a1c686a0462',
    messagingSenderId: '580433160519',
    projectId: 'ecologistapp-37663',
    databaseURL: 'https://ecologistapp-37663-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecologistapp-37663.appspot.com',
    iosClientId: '580433160519-m1e27jtvng9rgrib8plco2d5tj9nd0j1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecologistApp',
  );
}
